apiVersion: v1
kind: Pod
metadata:
  name: php-northeurope
  labels:
    location: northeurope
spec:
  containers:
  - name: php-northeurope
    image: mohamman/php_we:v2
    env:
    - name: MYSQL_HOST
      value: "CHANHEME"
    - name: MYSQL_USERNAME
      value: "CHANGEME"
    - name: MYSQL_PASSWORD
      value: "CHANGEME"
    - name: DATABASE_NAME
      value: "CHANGEME"
    - name: NODE_NAME
      valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
            fieldRef:
              fieldPath: metadata.name